obj-$(CONFIG_CLUSTER_PLUG)	:= cluster_plug.o
obj-$(CONFIG_MSM_SLEEPER) 	+= msm_sleeper.o
obj-$(CONFIG_MSM_HOTPLUG) 	+= msm_hotplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) 	+= alucard_hotplug.o
obj-$(CONFIG_ASMP)		+= autosmp.o
